#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr
bspc monitor eDP1 -d I II III

bspc monitor HDMI-0 -d IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config top_monocle_padding 8
bspc config bottom_monocle_padding 8
bspc config right_monocle_padding 8
bspc config left_monocle_padding 8

bspc config active_border_color "#5E81AC"
bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#434C5E"




bspc rule -a Blueberry.py state=floating
bspc rule -a Zathura state=tiled
bspc rule -a floating_term state=floating
bspc rule -a sticky_st sticky=on state=floating
bspc desktop ^3 --layout monocle

startup
